# Generated by Django 4.1 on 2022-08-05 02:57

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Company",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=50)),
                ("address", models.CharField(default="", max_length=100)),
                ("nit", models.PositiveBigIntegerField()),
                ("phone", models.PositiveBigIntegerField()),
            ],
        ),
    ]
